# Generated by Django 4.2.23 on 2025-08-04 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultpricingrule',
            options={'ordering': ['coverage_min'], 'verbose_name': 'Default Pricing Rule', 'verbose_name_plural': 'Default Pricing Rules (System-wide)'},
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='color',
            field=models.BooleanField(choices=[(True, 'Color'), (False, 'Black & White')], help_text='Whether this rule applies to color or black & white documents'),
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost in dollars for this coverage range', max_digits=10),
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='coverage_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum coverage percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='coverage_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum coverage percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is currently active'),
        ),
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='reason',
            field=models.CharField(help_text="Description of this pricing rule (e.g., 'Light text coverage')", max_length=255),
        ),
    ]
