# Generated by Django 4.2.23 on 2025-08-07 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0002_alter_defaultpricingrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpricingrule',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Cost in pesos for this coverage range', max_digits=10),
        ),
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text='Name of the uploaded document', max_length=255)),
                ('page_count', models.PositiveIntegerField(help_text='Total number of pages analyzed')),
                ('color_page_count', models.PositiveIntegerField(default=0, help_text='Number of color pages')),
                ('bw_page_count', models.PositiveIntegerField(default=0, help_text='Number of black & white pages')),
                ('overall_cost', models.DecimalField(decimal_places=2, help_text='Total cost for the document', max_digits=10)),
                ('analysis_result', models.JSONField(help_text='Detailed analysis results for each page')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='File extension (pdf, jpg, png, etc.)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('user', models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Analysis',
                'verbose_name_plural': 'Document Analysis History',
                'ordering': ['-created_at'],
            },
        ),
    ]
