# Generated by Django 4.2.23 on 2025-08-12 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0003_alter_defaultpricingrule_cost_documentanalysis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costsetting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='costsetting',
            name='business_owner',
            field=models.ForeignKey(blank=True, help_text='Business owner who sets this pricing rule', limit_choices_to={'userprofile__role__in': ['business_owner', 'super_admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='costsetting',
            unique_together={('business_owner', 'color', 'coverage_min', 'coverage_max')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('regular', 'Regular User'), ('business_owner', 'Business Owner'), ('super_admin', 'Super Administrator')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='costsetting',
            name='user',
        ),
    ]
