# Generated by Django 4.2.23 on 2025-08-12 07:15

from django.db import migrations
from django.contrib.auth.models import User

def create_user_profiles(apps, schema_editor):
    """Create UserProfile for all existing users and set default roles"""
    UserProfile = apps.get_model('analyzer', 'UserProfile')
    User = apps.get_model('auth', 'User')
    
    for user in User.objects.all():
        profile, created = UserProfile.objects.get_or_create(
            user=user,
            defaults={'role': 'regular'}
        )
        if created:
            print(f"Created profile for user: {user.username}")

def assign_business_owners_to_cost_settings(apps, schema_editor):
    """Assign the first user as business_owner for existing CostSetting records"""
    CostSetting = apps.get_model('analyzer', 'CostSetting')
    User = apps.get_model('auth', 'User')
    
    # Get the first user or create a default admin user
    first_user = User.objects.first()
    if first_user:
        # Update all CostSetting records to have the first user as business_owner
        CostSetting.objects.filter(business_owner__isnull=True).update(business_owner=first_user)
        print(f"Assigned {first_user.username} as business_owner for existing cost settings")

def reverse_migration(apps, schema_editor):
    """Reverse the migration if needed"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_costsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_migration),
        migrations.RunPython(assign_business_owners_to_cost_settings, reverse_migration),
    ]
