# Generated by Django 4.2.23 on 2025-08-12 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0005_auto_20250812_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsetting',
            name='business_owner',
            field=models.ForeignKey(help_text='Business owner who sets this pricing rule', limit_choices_to={'userprofile__role__in': ['business_owner', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
