# Generated by Django 4.2.23 on 2025-08-12 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0006_alter_costsetting_business_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOwnerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(help_text='Official business name', max_length=200)),
                ('business_type', models.CharField(help_text='Type of business (e.g., Print Shop)', max_length=100)),
                ('business_address', models.TextField(help_text='Complete business address')),
                ('business_phone', models.CharField(help_text='Business contact phone', max_length=20)),
                ('business_email', models.EmailField(help_text='Business email address', max_length=254)),
                ('business_registration_number', models.CharField(blank=True, help_text='DTI/SEC/CDA registration number', max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax Identification Number', max_length=20, null=True)),
                ('years_in_operation', models.PositiveIntegerField(help_text='Years the business has been operating')),
                ('monthly_volume', models.CharField(choices=[('low', 'Low (1-100 documents/month)'), ('medium', 'Medium (100-500 documents/month)'), ('high', 'High (500+ documents/month)')], help_text='Expected monthly document volume', max_length=10)),
                ('business_description', models.TextField(help_text='Description of business and pricing needs')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special pricing requirements', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Owner Request',
                'verbose_name_plural': 'Business Owner Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
