# Generated by Django 4.2.23 on 2025-08-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_requeststatuschange_requestmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststatuschange',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='requeststatuschange',
            name='request',
        ),
        migrations.DeleteModel(
            name='RequestMessage',
        ),
        migrations.DeleteModel(
            name='RequestStatusChange',
        ),
    ]
