# Generated by Django 4.2.25 on 2025-10-14 21:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0010_requestmessage_requeststatuschange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costsetting',
            options={'ordering': ['paper_size', 'coverage_min']},
        ),
        migrations.AlterModelOptions(
            name='defaultpricingrule',
            options={'ordering': ['paper_size', 'coverage_min'], 'verbose_name': 'Default Pricing Rule', 'verbose_name_plural': 'Default Pricing Rules (System-wide)'},
        ),
        migrations.AlterUniqueTogether(
            name='costsetting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='defaultpricingrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='costsetting',
            name='paper_size',
            field=models.CharField(choices=[('short', 'Short Bond Paper (8.5" x 11")'), ('long', 'Long Bond Paper (8.5" x 13")'), ('a4', 'A4 Size (210mm x 297mm)')], default='short', help_text='Paper size for this pricing rule', max_length=10),
        ),
        migrations.AddField(
            model_name='defaultpricingrule',
            name='paper_size',
            field=models.CharField(choices=[('short', 'Short Bond Paper (8.5" x 11")'), ('long', 'Long Bond Paper (8.5" x 13")'), ('a4', 'A4 Size (210mm x 297mm)')], default='short', help_text='Paper size for this pricing rule', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='costsetting',
            unique_together={('business_owner', 'color', 'paper_size', 'coverage_min', 'coverage_max')},
        ),
        migrations.AlterUniqueTogether(
            name='defaultpricingrule',
            unique_together={('color', 'paper_size', 'coverage_min', 'coverage_max')},
        ),
    ]
