# Generated by Django 4.2.25 on 2025-10-15 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzer', '0011_alter_costsetting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(choices=[('short', 'Short Bond Paper (8.5" x 11")'), ('long', 'Long Bond Paper (8.5" x 13")'), ('a4', 'A4 Size (210mm x 297mm)')], help_text='Paper size used for printing', max_length=10)),
                ('copies', models.PositiveIntegerField(default=1, help_text='Number of copies printed')),
                ('cost_per_copy', models.DecimalField(decimal_places=2, help_text='Cost per single copy', max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue from this print job (cost_per_copy × copies)', max_digits=10)),
                ('status', models.CharField(choices=[('queued', 'Queued for Printing'), ('printing', 'Currently Printing'), ('completed', 'Print Completed'), ('cancelled', 'Print Cancelled')], default='queued', help_text='Current status of the print job', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True, help_text='When the print job was queued')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the print job was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the print job')),
                ('analysis', models.ForeignKey(help_text='Original document analysis', on_delete=django.db.models.deletion.CASCADE, related_name='printed_copies', to='analyzer.documentanalysis')),
                ('business_owner', models.ForeignKey(help_text='Business owner who earns revenue from this print', limit_choices_to={'userprofile__role__in': ['business_owner', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='printed_revenue', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(help_text='User who initiated the print job', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Printed Document',
                'verbose_name_plural': 'Print History & Revenue',
                'ordering': ['-queued_at'],
            },
        ),
    ]
